name: Deploy Auth Service to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - "backend/auth-service/**"
  workflow_dispatch: # ✅ Perbaiki ini juga, sebelumnya kamu menulis: `workflow_dispatch: 🟢`
    {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

      # ✅ Build and push ke Artifact Registry
      - name: Build and Push Docker image
        run: |
          docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/lung-app/auth-service ./backend/auth-service
          docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/lung-app/auth-service

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy auth-service \
            --image asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/lung-app/auth-service \
            --region asia-southeast2 \
            --platform managed \
            --allow-unauthenticated
